contributors:
  - name: "COMET"
    nameType: "Organizational"
    contributorType: "Producer"

resources:
  - relatedIdentifier: "10.82461/bpzr-jd55"
    relatedIdentifierType: "DOI"
    relationType: "IsDocumentedBy"
    resourceTypeGeneral: "Project"
  - relatedIdentifier: "https://huggingface.co/datasets/cometadata/datacite-procedural-resource-type-general-reclassifications-datacite-enrichment-format"
    relatedIdentifierType: "URL"
    relationType: "IsDerivedFrom"
    resourceTypeGeneral: "Dataset"
